#!/usr/bin/env python3
"""Hyperparameter sweep manager for BioReview SFT training.

Subcommands:
  generate-configs  Create variant YAML configs + sweep manifest from a definition
  log-result        Append evaluation results from .summary.json to sweep CSV
  show-results      Print sorted results table from sweep CSV

Usage:
  # Generate sweep configs from definition YAML:
  python scripts/sweep_manager.py generate-configs \
      --sweep configs/sweep/stage1_14b.yaml

  # Log a result after training + inference completes:
  python scripts/sweep_manager.py log-result \
      --summary results/sft_eval/model_val_lr_1e4.summary.json \
      --tag lr_1e4 \
      --csv results/sweep_results.csv

  # Show all sweep results:
  python scripts/sweep_manager.py show-results \
      --csv results/sweep_results.csv

Sweep definition YAML format:
  base_config: configs/qwen2.5_14b_qlora.yaml
  output_dir: configs/sweep/stage1_14b
  experiments:
    - tag: baseline
    - tag: lr_1e4
      overrides:
        training.learning_rate: 1.0e-4
    - tag: ep5
      overrides:
        training.num_train_epochs: 5
"""

from __future__ import annotations

import argparse
import copy
import csv
import json
import sys
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# generate-configs
# ---------------------------------------------------------------------------


def _set_nested(d: dict, dotted_key: str, value) -> None:
    """Set a value in a nested dict using dot-notation key."""
    keys = dotted_key.split(".")
    for k in keys[:-1]:
        d = d.setdefault(k, {})
    d[keys[-1]] = value


def _get_nested(d: dict, dotted_key: str, default=None):
    """Get a value from nested dict using dot-notation key."""
    keys = dotted_key.split(".")
    for k in keys:
        if not isinstance(d, dict):
            return default
        d = d.get(k, default)
    return d


def generate_configs(args: argparse.Namespace) -> None:
    """Generate variant configs from a sweep definition YAML."""
    sweep_path = args.sweep
    if not sweep_path.exists():
        print(f"ERROR: sweep definition not found: {sweep_path}", file=sys.stderr)
        raise SystemExit(1)

    sweep_def = yaml.safe_load(sweep_path.read_text(encoding="utf-8"))

    base_config_path = Path(sweep_def["base_config"])
    if not base_config_path.is_absolute():
        # Resolve relative to sweep definition file
        base_config_path = sweep_path.parent / base_config_path
    if not base_config_path.exists():
        print(f"ERROR: base config not found: {base_config_path}", file=sys.stderr)
        raise SystemExit(1)

    base_config = yaml.safe_load(base_config_path.read_text(encoding="utf-8"))

    output_dir = Path(sweep_def.get("output_dir", "configs/sweep"))
    if not output_dir.is_absolute():
        output_dir = sweep_path.parent / output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    experiments = sweep_def.get("experiments", [])
    if not experiments:
        print("ERROR: no experiments defined in sweep YAML.", file=sys.stderr)
        raise SystemExit(1)

    manifest_rows = []
    base_output_dir = base_config.get("output", {}).get("dir", "models/sweep")

    for idx, exp in enumerate(experiments, 1):
        tag = exp["tag"]
        overrides = exp.get("overrides", {})

        variant = copy.deepcopy(base_config)

        # Apply overrides
        for key, value in overrides.items():
            _set_nested(variant, key, value)

        # Bug fix #10: auto-set lora_alpha = 2 * lora_r
        if "lora.r" in overrides:
            new_r = overrides["lora.r"]
            variant["lora"]["lora_alpha"] = 2 * new_r

        # Bug fix #8: unique output dir per variant
        variant.setdefault("output", {})["dir"] = f"{base_output_dir}_{tag}"

        # Write variant config
        config_path = output_dir / f"{tag}.yaml"
        header = (
            f"# Auto-generated by sweep_manager.py\n"
            f"# Base: {base_config_path.name}\n"
            f"# Tag: {tag}\n"
        )
        if overrides:
            override_str = ", ".join(f"{k}={v}" for k, v in overrides.items())
            header += f"# Overrides: {override_str}\n"
        header += "\n"

        config_path.write_text(
            header + yaml.dump(variant, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )

        manifest_rows.append(
            {
                "index": idx,
                "tag": tag,
                "config_path": str(config_path),
                "base_model": _get_nested(variant, "model.name", ""),
                "output_dir": variant["output"]["dir"],
                "overrides": (
                    "; ".join(f"{k}={v}" for k, v in overrides.items())
                    if overrides
                    else ""
                ),
            }
        )
        print(f"  [{idx}] {tag}: {config_path}")

    # Write manifest CSV
    manifest_path = output_dir / "sweep_manifest.csv"
    with manifest_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["index", "tag", "config_path", "base_model", "output_dir", "overrides"],
        )
        writer.writeheader()
        writer.writerows(manifest_rows)

    print(f"\nGenerated {len(experiments)} configs in {output_dir}/")
    print(f"Manifest: {manifest_path}")
    n = len(experiments)
    print(f"\nRecommended SLURM array spec: --array=1-{n}%2")


# ---------------------------------------------------------------------------
# log-result
# ---------------------------------------------------------------------------


def log_result(args: argparse.Namespace) -> None:
    """Append evaluation result from .summary.json to sweep CSV."""
    if not args.summary.exists():
        print(f"ERROR: summary not found: {args.summary}", file=sys.stderr)
        raise SystemExit(1)

    data = json.loads(args.summary.read_text(encoding="utf-8"))
    metrics = data.get("eval_metrics", {})

    row = {
        "tag": args.tag,
        "model_dir": data.get("model_dir", ""),
        "f1_micro": metrics.get("f1_micro", ""),
        "recall_overall": metrics.get("recall_overall", ""),
        "precision_overall": metrics.get("precision_overall", ""),
        "recall_major": metrics.get("recall_major", ""),
        "n_articles": metrics.get("n_articles", ""),
        "n_tool_concerns": metrics.get("n_tool_concerns", ""),
        "processed": data.get("processed", ""),
        "total_time": data.get("total_time", ""),
        "summary_file": str(args.summary),
    }

    csv_path = args.csv
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not csv_path.exists() or csv_path.stat().st_size == 0

    with csv_path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        if write_header:
            writer.writeheader()
        writer.writerow(row)

    f1 = metrics.get("f1_micro", "N/A")
    print(f"Logged: {args.tag} → F1={f1} → {csv_path}")


# ---------------------------------------------------------------------------
# show-results
# ---------------------------------------------------------------------------


def show_results(args: argparse.Namespace) -> None:
    """Print sorted results table from sweep CSV."""
    if not args.csv.exists():
        print(f"ERROR: CSV not found: {args.csv}", file=sys.stderr)
        raise SystemExit(1)

    with args.csv.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print("No results in CSV.")
        return

    # Sort by F1 descending
    def sort_key(r):
        try:
            return float(r.get("f1_micro", 0))
        except (ValueError, TypeError):
            return 0.0

    rows.sort(key=sort_key, reverse=True)

    print(f"\nSweep Results ({len(rows)} experiments)")
    print(f"Source: {args.csv}\n")
    print("| # | Tag | F1 | Recall | Precision | Recall(major) | Articles |")
    print("|---|-----|---:|-------:|----------:|--------------:|---------:|")

    for i, r in enumerate(rows, 1):
        tag = r.get("tag", "?")
        f1 = r.get("f1_micro", "—")
        rec = r.get("recall_overall", "—")
        prec = r.get("precision_overall", "—")
        rmaj = r.get("recall_major", "—")
        n = r.get("n_articles", "—")
        # Format numbers if present
        try:
            f1 = f"{float(f1):.4f}"
        except (ValueError, TypeError):
            pass
        try:
            rec = f"{float(rec):.4f}"
        except (ValueError, TypeError):
            pass
        try:
            prec = f"{float(prec):.4f}"
        except (ValueError, TypeError):
            pass
        try:
            rmaj = f"{float(rmaj):.4f}"
        except (ValueError, TypeError):
            pass
        print(f"| {i} | {tag} | {f1} | {rec} | {prec} | {rmaj} | {n} |")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Hyperparameter sweep manager for BioReview SFT."
    )
    sub = parser.add_subparsers(dest="command")

    # generate-configs
    gen = sub.add_parser("generate-configs", help="Create variant configs from sweep definition.")
    gen.add_argument(
        "--sweep",
        type=Path,
        required=True,
        help="Sweep definition YAML file.",
    )

    # log-result
    log = sub.add_parser("log-result", help="Append eval result to sweep CSV.")
    log.add_argument("--summary", type=Path, required=True, help=".summary.json file.")
    log.add_argument("--tag", required=True, help="Experiment tag.")
    log.add_argument(
        "--csv",
        type=Path,
        default=Path("results/sweep_results.csv"),
        help="Sweep results CSV path.",
    )

    # show-results
    show = sub.add_parser("show-results", help="Print sorted results table.")
    show.add_argument(
        "--csv",
        type=Path,
        default=Path("results/sweep_results.csv"),
        help="Sweep results CSV path.",
    )

    args = parser.parse_args()

    if args.command == "generate-configs":
        generate_configs(args)
    elif args.command == "log-result":
        log_result(args)
    elif args.command == "show-results":
        show_results(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
